// src/core/utilities/errorCodes.ts

/**
 * Standardized error codes for debugging and error tracking
 * Format: CATEGORY + 3-digit number
 */
export const ErrorCodes = {
    // Authentication errors (AUTH001-AUTH099)
    AUTH_INVALID_CREDENTIALS: 'AUTH001',
    AUTH_EMAIL_EXISTS: 'AUTH002',
    AUTH_USERNAME_EXISTS: 'AUTH003',
    AUTH_PHONE_EXISTS: 'AUTH004',
    AUTH_ACCOUNT_SUSPENDED: 'AUTH005',
    AUTH_ACCOUNT_LOCKED: 'AUTH006',
    AUTH_TOKEN_INVALID: 'AUTH007',
    AUTH_TOKEN_EXPIRED: 'AUTH008',
    AUTH_UNAUTHORIZED: 'AUTH009',
    AUTH_INVALID_TOKEN: 'AUTH010',
    
    // User errors (USER001-USER099)
    USER_NOT_FOUND: 'USER001',
    USER_CREDENTIALS_NOT_FOUND: 'USER002',
    USER_EMAIL_NOT_VERIFIED: 'USER003',
    USER_PHONE_NOT_VERIFIED: 'USER004',
    
    // Password errors (PASS001-PASS099)
    PASS_INCORRECT_OLD: 'PASS001',
    PASS_SAME_AS_OLD: 'PASS002',
    PASS_RESET_TOKEN_INVALID: 'PASS003',
    PASS_RESET_TOKEN_EXPIRED: 'PASS004',
    
    // Verification errors (VRFY001-VRFY099)
    VRFY_EMAIL_ALREADY_VERIFIED: 'VRFY001',
    VRFY_PHONE_ALREADY_VERIFIED: 'VRFY002',
    VRFY_CODE_INVALID: 'VRFY003',
    VRFY_CODE_EXPIRED: 'VRFY004',
    VRFY_TOO_MANY_ATTEMPTS: 'VRFY005',
    VRFY_RATE_LIMITED: 'VRFY006',
    VRFY_TOKEN_INVALID: 'VRFY007',
    VRFY_TOKEN_EXPIRED: 'VRFY008',
    VRFY_ALREADY_VERIFIED: 'VRFY009',
    VRFY_RATE_LIMIT_EXCEEDED: 'VRFY010',
    VRFY_INVALID_TOKEN: 'VRFY011',
    VRFY_NO_CODE_FOUND: 'VRFY012',
    VRFY_INVALID_CODE: 'VRFY013',
    
    // Validation errors (VALD001-VALD099)
    VALD_MISSING_FIELDS: 'VALD001',
    VALD_INVALID_EMAIL: 'VALD002',
    VALD_INVALID_PHONE: 'VALD003',
    VALD_INVALID_ROLE: 'VALD004',
    VALD_INVALID_INPUT: 'VALD005',
    VALD_INVALID_PASSWORD: 'VALD006',
    
    // Server errors (SRVR001-SRVR099)
    SRVR_DATABASE_ERROR: 'SRVR001',
    SRVR_EMAIL_SEND_FAILED: 'SRVR002',
    SRVR_SMS_SEND_FAILED: 'SRVR003',
    SRVR_TRANSACTION_FAILED: 'SRVR004',
    SRVR_DATA_INTEGRITY_ERROR: 'SRVR005',
    SRVR_GENERIC_ERROR: 'SRVR099',
};